### ISSUE TITLE
registration-free COM may be failing in unit tests on clean machine

### ISSUE THREAD

**Issue by michaelcfanning** [Microsoft/binskim#127]

**Comment by Evmaus-MS** [comment]
I can provide a workaround for this from earlier today.

Clean machine, install VS2017, sync master, run tests -> tests fail with COM class missing/not registered.

Install VS2015.3 on the machine, run tests -> tests will pass.

Something about a VS2015 install fixes the issue, although I'm not sure what's the root cause.

**Comment by paddymcd-MSFT** [comment]
It is because 2017 is the first VS to install side by side and so efforts were made across the entire product to remove as many uses  / dependency upon system wide registrations.

So no more registering COM servers where possible.

p

Sent from my Windows 10 phone

**Comment by michaelcfanning** [comment]
so VS2015 is registering MSDIA140.dll. our tests could do this as well (and unregister too), though this would require admin elevation.

**Comment by Evmaus-MS** [comment]
Now a duplicate of:  https://github.com/Microsoft/binskim/issues/173

We'll track this there.

**Comment by denchik778** [comment]
Forkplyer_tv
