### ISSUE TITLE
discover code signed state

### ISSUE THREAD

**Issue by ElJefeDSecurIT** [Microsoft/binskim#166]
is it possible to have binskim also check for the code signing status, and what cipher was used? and maybe any certificate associated with it? would like to see this discover and reflect the code signing stuff around a binary.

**Comment by Evmaus-MS** [comment]
So at the moment, I believe it *should* flag both the cipher used to sign the binary, and the hash algorithm used to hash the binary if the cipher or hash algorithm used to sign the binary isn't trusted by WinTrustVerify.  I *think* the same should go if the certificate itself is incorrectly signed/has an insecure hash algorithm, but I'd need to investigate that.

However, more generic code signing status (signed/not signed) or certificate trust information is unlikely to make it into the default behavior:  We've actually intentionally removed checking if the certificate chain is trusted on the current machine, and we've always intentionally avoided flagging binaries that aren't signed as an 'error'.

The first is because there are isolated environments where you may want to scan binaries signed for use elsewhere, but you don't want them to be trusted to run on the machine (isolated build environments fall into this category).

The second restriction is because BinSkim will often run against bits from a non-shipping build (e.x. during a pull request), and there are teams that break their PR builds on any new BinSkim issue--so flagging unsigned binaries is a non-starter for a separate group of use cases.

---

All that being said, I'm curious about exactly what you're interested in here/what the use case is--are you looking for *unsigned* binaries, binaries signed with insecure algorithms, just to get data about what algorithms binaries happen to be signed with, or something else?  There's *definitely* a case to be made for making optional/non-default behaviors which flag unsigned binaries or flag against an untrusted certificate chain.

**Comment by Evmaus-MS** [comment]
Hey--

I'm happy to chat more about the use case here to see if there's changes that can be made to enable this, but in the meantime I'm going to close this question as answered.

--Everett Maus
