### ISSUE TITLE
Can't load default configuration for analyze

### ISSUE THREAD

**Issue by craigktreasure** [microsoft/binskim#295]
#### Info

OS:        Windows
Version: BinSkim PE/MSIL Analysis Driver 1.6.1.0

#### Description

I've exported a default configuration file by running `BinSkim.exe exportConfig .\Desktop\binskim-settings.json`. Then, I'm trying to use the default configuration file I just exported by running `BinSkim.exe analyze --recurse --force --output .\Desktop\BinSkim.sarif --config .\Desktop\binskim-settings.json <my specifiers>`. 

The result is:
```shell
Analyzing...
BINSKIM : error ERR999.UnhandledEngineException : An exception was raised during analysis. (Unable to cast object of type 'System.Int32' to type 'System.String'.)

Analysis did not complete due to one or more unrecoverable execution conditions.
Unexpected fatal runtime condition(s) observed: ExceptionInEngine
```

Also, the configuration file exported by default is a json file. However, the docs [here](https://github.com/microsoft/binskim/blob/master/docs/UserGuide.md#-c---config) seem to be under the impression that it should be an XML file.

**Comment by eddynaka** [comment]
Hi @craigktreasure , sorry for the delay.
Found the issue and the fix is in the Sarif.SDK.
For now, you can:
- switch to xml configuration
- keep using  json, but for each value, instead of using 0,1,2,4 use the string (Default, Error, etc).

With that, the properties will be read normally.
Will close this as soon as the PR gets merged in sarif.sdk and binskim.
