### ISSUE TITLE
BinSkim -- Unclear output when PDBs not available

### ISSUE THREAD

**Issue by scovetta** [Microsoft/binskim#39]
I ran BinSkim and Binscope against the same binary and found an important difference.

When BinScope doesn't find private symbols (and is therefore unable to perform various analyses), it fails that check with a message like:

```
<FILE> cannot be processed by ATLVersionCheck, because ATLVersionCheck requires private symbols which BinScope was not able to find next to the binary or on your symbol path (%_NT_SYMBOL_PATH% or /SymPath). The specific error generated by MSDIA while resolving symbols was: E_PDB_NOT_FOUND (File not found) Obtain matching private symbols for the binaries being tested and run BinScope again.
```

When BinSkim is run against the same binary, I see a more cryptic:

```
<FILE>: error BA2007: '<FILE>' contains code from an unknown language, preventing a comprehensive analysis of the compiler warning settings. The language could not be identified for the following modules: <file> ... 

<FILE>: error BA2011: '<FILE>' contains code from an unknown language, preventing a comprehensive analysis of the stack protector buffer security features. The language could not be identified for the following modules: <file> ...

Analysis finished but was not complete due to non-fatal runtime errors.
Unexpected runtime condition(s) observed: RuleNotApplicableToTarget
```

Are these error messages "the same" -- if so, can the user be given more information (and direction to include symbol files)? Without this, the user will be more likely to think they "passed" -- under the presumption that no output is "good".

**Comment by michaelcfanning** [comment]
Hello! BinSkim should provide a similar 'pdb is missing' message. What's odd here is that I believe the BinSkim message you are seeing indicates that, in fact, it is able to resolve the PDB, otherwise it couldn't try to dig into the compilands and find an apparently unknown language. 

It is possible you've configured BinSkim to pull in symbols somehow? Note that BinSkim (as opposed to Binscope) requires very explicit configuration of sympathy, etc., in order to operate. BinSkim operates this way to prevent some unexpected slowdowns users don't like when the tool picks up the symbol path from the environment. 

Can you send me a repro file by mail? Would be glad to look at this further.

**Comment by michaelcfanning** [comment]
I have verified that Binskim is emitting clear messages when PDBs are missing, If you still see confusing output, please feel free to reopen this issue.
