### ISSUE TITLE
"Control-flow Enforcement Technology (CET) Shadow Stack mitigation" , BA2025 should not be applied for arm64 binaries

### ISSUE THREAD

**Issue by chipitsine** [microsoft/binskim#508]
```
C:\i\openvpn-pipeline-artifacts\arm64\openvpn.exe: warning BA2025: 'openvpn.exe' does not enable the Control-flow Enforcement Technology (CET) Shadow Stack mitigation. To resolve this issue, pass /CETCOMPAT on the linker command lines.
```

however, CET is not available for arm64

**Comment by michaelcfanning** [comment]
@marmegh, can you fix this issue?

This issue is best resolved by first producing a test binary relevant to the problem, i.e., an ARM64 binary built by a recent VS. There are a few things to learn about how BinSkim uses these checked in test files, @eddynaka, @yongyan-gh, and @shaopeng-gh can advice. You can also use the test binary generation to prove to yourself that arm64 is incompatible with this security feature: providing /CETCOMPAT when compiling an ARM64 binary should error out (or at least display a warning about an erroneous switch passed).

The actual fix in the rule s/be trivial, the substance here is mostly in the testing. :)
