### ISSUE TITLE
BA2004 - EnableSecureSourceCodeHashing: Provide more info on the indirect dependency in the error message 

### ISSUE THREAD

**Issue by shaopeng-gh** [microsoft/binskim#848]
To triage if we want to:
provide more info on the dependency that is causing the failure in the error message.

this is what user currently get for error:
```
“The following modules are out of policy: Microsoft (R) Optimizing Compiler : cxx : 19.34.31940.0 : [directly linked] (AssemblyAttributes.obj)”
```
User has no idea why AssemblyAttributes.obj fail the rule because they did provide SHA_256 flag for it

we have this extra info available if we want to provide to the user:
```
D:\NugetCache\[package_name]\[package_version]\ref\mscorlib.dll
```
If we want, we need to see where to put it.
e.g.
“The following modules are out of policy: Microsoft (R) Optimizing Compiler : cxx : 19.34.31940.0 : [directly linked] (AssemblyAttributes.obj) [lib path: D:\NugetCache\[package_name]\[package_version]\ref\mscorlib.dll]”

**Comment by nkidd-intc** [comment]
I am running into the same kind of error, involving **.NETFramework,Version=v4.8.AssemblyAttributes.obj**. This seems to be compiled using a generated **.NETFramework,Version=v4.8.AssemblyAttributes.cpp** , that appears in intermediate build options. It's my understanding that my C++/CLI wrapper project is linking against mscorlib.dll, and this generated .cpp file is used to inform the DLL loader which version of .NET to use.

Does anybody have any suggestions on how to resolve the BA2004 error for scenarios like this?

**Comment by shaopeng-gh** [comment]
Have no insight unless debug the file, but first step would be make sure using public VS 2022 release and also the latest, e.g. currently Version 17.7.6

**Comment by nkidd-intc** [comment]
I'm produced the error with both Microsoft Visual Studio Professional 2022 (64-bit) / 17.6.3 and with 17.7.6. Also updated to latest MSVC v143/v14.37.-17.7. Even with these updates, binskim is reporting the BA2004 error.

The .vcxproj is building a C++/CLI DLL. Visual Studio and project are generating the .NETFramework,Version=v4.8.AssemblyAttributes.cpp file in the obj directory, where the .NETFramework,Version=v4.8.AssemblyAttributes.obj also appears. 

file.dll: error BA2004: 'file.dll' is a native binary that directly compiles and links one or more object files which were hashed using an insecure checksum algorithm (MD5). MD5 is subject to collision attacks and its use can compromise supply chain integrity. Pass '/ZH:SHA_256' on the cl.exe command-line to enable secure source code hashing. The following modules are out of policy:
Microsoft (R) Optimizing Compiler : cxx : 19.37.32825.0 : [directly linked] (.NETFramework,Version=v4.8.AssemblyAttributes.obj)`
`

**Comment by shaopeng-gh** [comment]
The problem could be the project was created with older version of Visual studio with older template.

could you check how it looks
1.  create a new project with the latest version of Visual studio 2022. Build and run Binskim on it
build using right click solution, and scan using Binskim
2. gradually copy your source code in, and find the point it start to complain about the AssemblyAttributes.obj

I remember this issue does not happen with newly created project form official template.
My guess it is related to the template, or the build script if you are using custom build script other than the right click and build.

Thanks for reporting, Looking forward to hear from you on this,

**Comment by matthew-wozniczka** [comment]
I'm trying to debug why binskim is giving me this error for an object file compiled w/ the following command:

`C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.39.33519\bin\HostX64\x64\CL.exe /c <Many /I & /IC options> /Zi /nologo /W3 /WX- /diagnostics:column /MP /O2 /D UNICODE /D _UNICODE /D WIN64 /D _WIN64 /D NDEBUG /D _LIB /D SIMBA /D _CRT_SECURE_NO_WARNINGS /D _VC80_UPGRADE=0x0710 /D _WINDLL /D _UNICODE /D UNICODE /GF /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR- /Fo"w2016\vs2022\release64md\\" /Fd"w2016\vs2022\release64md\XMODBC642.pdb" /external:W3 /Gd /TP /wd4245 /FC /errorReport:queue <Many .cpp files, only one of which creates an object file which is complained about by binskim>`

There's no `/ZH` option specified, https://learn.microsoft.com/en-us/cpp/build/reference/zh?view=msvc-170 claims "The /ZH:SHA_256 option is the default in Visual Studio 2022 version 17.0 and later", and from https://blog.knatten.org/2022/08/26/microsoft-c-versions-explained/ I gather that `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.39.33519\bin\HostX64\x64\CL.exe` comes from a version of visual studio later than 17.0, so I don't get it?

I don't understand this 'indirect dependency' that this issue speaks of; isn't the problem solely due to how the offending object file was compiled?

**Comment by shaopeng-gh** [comment]
Just an update 
https://github.com/microsoft/binskim/issues/974
I believe we are looking to close this noise gap, I have created a PR in that issue.
Closing this one as duplicated.
